version: '2'
services:
    worktajm-app:
        image: worktajm
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://worktajm-mysql:3306/worktajm?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=worktajm-elasticsearch:9300
        ports:
            - 8080:8080
    worktajm-mysql:
        extends:
            file: mysql.yml
            service: worktajm-mysql
    worktajm-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: worktajm-elasticsearch
